version: "3"

services:
  web:
    image: bluefunny/mcsmanager:web-9
    container_name: mcsmanager-web
    environment:
      - TZ=Asia/Shanghai
    volumes:
      # MCSManager Web log storage directory
      - ./data/logs/web:/opt/web/logs
      # MCSManager Web data storage directory
      - ./data/data/web:/opt/web/data
    # port:
    #   - 23333:23333 
    network_mode: host

  daemon:
    image: bluefunny/mcsmanager:daemon-9
    container_name: mcsmanager-daemon
    environment:
      - TZ=Asia/Shanghai
    volumes:
      # MCSManager Daemon log storage directory
      - ./data/logs/daemon:/opt/daemon/logs
      # MCSManager Daemon data storage directory
      - ./data/data/daemon:/opt/daemon/data
    # port:
    #   - 24444:24444
    network_mode: host