version: "3"

services:
  daemon:
    image: bluefunny/mcsmanager:daemon-9
    container_name: mcsmanager-daemon
    environment:
      - TZ=Asia/Shanghai
    volumes:
      # MCSManager Daemon 日志存储目录
      - ./data/logs/daemon:/opt/daemon/logs
      # MCSManager Daemon 数据存储目录
      - ./data/data/daemon:/opt/daemon/data
    # port:
    #   - 24444:24444
    network_mode: host